docs/Lições.md
mkdocs.yml

Adiciona lições aprendidas ao gitPages.

Lições aprendidas Missão 1

---

docs/projeto-visao.md

#12 - Matriz de Comunicação
Fazendo as alterações solicitadas pelo professor.

#12 matriz de comunicacao

---

docs/projeto-visao.md

#11 - Planejamento das Fases e/ou Iterações do Projeto
- Definição das Entregas e Alinhamento ao Processo XP.

#11 planejamento das fases eou iterações do projeto

---

docs/projeto-visao.md

#10  Adição do líder estelar na tabela de organização do projeto

---

docs/rnf.md
mkdocs.yml

Requisitos nao funcionais

---

docs/missao2-mvp.md

Adição do MVP

---

docs/entrega-missao2.md
docs/licoes-missao2.md
mkdocs.yml

Pequenas correções

---

api/middlewares/GroupValidation.js
api/models/Grupo.js
api/routes/GrupoRoutes.js
api/routes/Router.js
api/services/Grupos/CreateGroup.js
api/services/Grupos/GetGroups.js

Adicionando a funcionalidade de grupos.

Crud grupos

---

api/middlewares/PasswordGenerator.js
api/middlewares/ProfessorValidations.js
api/middlewares/SendMail.js
api/package-lock.json
api/package.json
api/reg_base_prof.http
api/routes/ProfessorRoutes.js
api/services/Professor/AunthenticateToken.js
api/services/Professor/AuthenticateTokenProf.js
api/services/Professor/DeleteProf.js
api/services/Professor/GenerateToken.js
api/services/Professor/GetProf.js
api/services/Professor/LoginProf.js
api/services/Professor/RegisterProf.js
api/services/Professor/UpdateProf.js
frontend/package-lock.json

CRUD Professor

---

api/middlewares/TurmaValidation.js
api/models/Turma.js
api/package-lock.json
api/package.json
api/reg_base_admin.http
api/routes/Router.js
api/routes/TurmaRoutes.js
api/services/Turma/DeleteTurma.js
api/services/Turma/GetTurma.js
api/services/Turma/GetTurmas.js
api/services/Turma/RegisterTurma.js

Crud turma

---

config/db.js

Consertando a conexao com o banco de dados.

fix: Consertando coneccao ao banco de dados

---

middlewares/AlunoValidation.js
middlewares/TurmaValidation.js
models/Aluno.js
routes/AlunoRoutes.js
routes/GrupoRoutes.js
routes/ProfessorRoutes.js
routes/Router.js
routes/TurmaRoutes.js
services/Aluno/ActivateRegister.js
services/Aluno/AuntheticateToken.js
services/Aluno/DeleteAluno.js
services/Aluno/GenerateToken.js
services/Aluno/GetAluno.js
services/Aluno/LoginAluno.js
services/Aluno/LoginTokenAluno.js
services/Aluno/RegisterAluno.js
services/Professor/GetProf.js
services/ProfessorAdmin/AunthenticateToken.js

Crud aluno

---

docs/healthnet-pbb.md
docs/licoes-missao3.md
docs/missao2-criterios-aceitacao.md
docs/missao2-mvp.md
docs/pontuacao.md
mkdocs.yml

Removendo correção monitor do mvp  e  Adicionando PBB e lições aprendidas

---

docs/entrega-missao3.md
mkdocs.yml

Adicionando vídeo da entrega da missão 3.

Adicionando vídeo da entrega 3

---

src/App.jsx
src/pages/exercicio/AtividadeDeTexto.jsx

Tela exercicio de texto

---

docker-compose.yml
models/RespostaTexto.js
routes/AlunoRoutes.js
routes/AtividadeRoutes.js
services/Atividades/CreateAtividadeTexto.js
services/Atividades/GetRespostaPorAtividade.js
services/Atividades/ResponderAtividadeTexto.js

Adicionando funcionalidade de atividades

Crud atividades

---

src/pages/dashboard/AdminDashboard.jsx
src/pages/lista-grupos/lista.jsx

Adicionando as alterações da home de admin

Consertando tela de admin

---

package-lock.json
package.json
src/components/grupo-card/GrupoCard.jsx
src/pages/lista-grupos/lista.jsx

Refatorando front grupos

---

middlewares/GroupValidation.js
routes/GrupoRoutes.js
services/Grupos/EditGrupo.js

Acessar a rota /grupo/<_id> com método PUT
O JSON deve conter as chaves:
- nome
- descricao
- capacidade

Rota para editar grupo

---

src/components/editar-aluno-modal/EditarAlunoModal.jsx
src/pages/lista-alunos/AlunosParaAdmin.jsx
src/pages/lista-alunos/AlunosParaProfessor.jsx

Adiciona modal para a confirmação de exclusão

---

Dockerfile
nginx.conf
src/context/AuthContext.jsx
src/pages/atividades/interpretador.jsx

Fork pro Base

---

docs/avaliacao-pbb-space.md
mkdocs.yml

Atividade ver val pbb

---

routes/AlunoRoutes.js
routes/ProfessorRoutes.js
services/Aluno/RegisterAluno.js
services/Professor/RegisterProf.js

Recuperar senha
